name: Verify Build Status & Build Functionality (Calling)
on:
  schedule:
    - cron: 0 5 * * * # runs at 6am CET DAILY
  workflow_dispatch:
  push:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: read
  issues: write

jobs:
 check-nightly-builds:
    name: Check Nightly Build failures
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nightly_build: [ 'Python', 'LinuxRelease', 'Android', 'Julia', 'Main', 'OSX', 'R', 'Swift', 'SwiftRelease', 'Windows' ]
    steps:
      - uses: actions/checkout@v4
      - run: pip install duckdb pandas
      - name: Create run status report for ${{ matrix.nightly_build }} nighlty-builds
        continue-on-error: true
        run: |
          # write list of last runs for specified workflow to a json file
          gh run list --repo duckdb/duckdb --workflow ${{ matrix.nightly_build }} \
            --json event,status,conclusion,name,createdAt,url \
            --event repository_dispatch > input_${{ matrix.nightly_build }}.json
          
          # count consecutive failures and create a run_status.md file
          python scripts/count_consecutive_failures.py input_${{ matrix.nightly_build }}.json --nightly_build ${{ matrix.nightly_build }}
